use_frameworks!

platform :ios, '8.0'

target 'TXServerAddressManager_Example' do
  pod 'TXServerAddressManager', :path => '../'

  target 'TXServerAddressManager_Tests' do
    inherit! :search_paths

    
  end
end
